WIP: Update to keycloak 20.0.0
daniel-frak/keycloak-user-migration pull request #68
Opened 2022-11-02 15:06 UTC by Guy-Incognito

I still need to update e2e tests

2022-11-08 09:28 UTC, Guy-Incognito commented
@daniel-frak  Rady for your review ;)

2022-11-10 14:53 UTC, daniel-frak requested changes

2022-11-10 14:53 UTC, daniel-frak commented on docker/e2e/cypress/integration/migrating_users.spec.js
> +        // TODO delete existing configured plugins
Could you elaborate on this TODO?

2022-11-10 14:53 UTC, daniel-frak commented on docker/e2e/cypress/integration/migrating_users.spec.js
> +        cy.wait(500);
This seems flakey. Are we sure there is no other way to do this than using `cy.wait(500)`?
If not, then I think a comment could be helpful explaining why the `wait` is needed.

2022-11-10 14:53 UTC, daniel-frak commented on docker/e2e/cypress/integration/migrating_users.spec.js
> +        cy.wait(500);
Ditto about `wait`.

2022-11-10 14:53 UTC, daniel-frak commented on docker/e2e/cypress/integration/migrating_users.spec.js
> +        cy.wait(1000);
Ditto about `wait`.

2022-11-10 14:57 UTC, daniel-frak commented
Thanks for the contribution!
That's quite an update to the Cypress tests, I'm glad I didn't have to do it :P

I just have some comments regarding the uses of `wait` and a lone `TODO`.

2022-11-10 20:20 UTC, daniel-frak commented
LGTM, thanks!

2022-11-10 20:20 UTC, merged